// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BuildRequestAbilityMethod.
const (
	PointBuy BuildRequestAbilityMethod = "point-buy"
	Roll     BuildRequestAbilityMethod = "roll"
	Standard BuildRequestAbilityMethod = "standard"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Defines values for SaveCharacterRequestProgressionType.
const (
	SaveCharacterRequestProgressionTypeMilestone SaveCharacterRequestProgressionType = "milestone"
	SaveCharacterRequestProgressionTypeXp        SaveCharacterRequestProgressionType = "xp"
)

// Defines values for SavedCharacterProgressionType.
const (
	SavedCharacterProgressionTypeMilestone SavedCharacterProgressionType = "milestone"
	SavedCharacterProgressionTypeXp        SavedCharacterProgressionType = "xp"
)

// AbilityEntry defines model for AbilityEntry.
type AbilityEntry struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// AbilityScores defines model for AbilityScores.
type AbilityScores struct {
	CHA int `json:"CHA"`
	CON int `json:"CON"`
	DEX int `json:"DEX"`
	INT int `json:"INT"`
	STR int `json:"STR"`
	WIS int `json:"WIS"`
}

// Attack defines model for Attack.
type Attack struct {
	Bonus  *int    `json:"bonus,omitempty"`
	Damage *string `json:"damage,omitempty"`
	Name   *string `json:"name,omitempty"`
	Range  *string `json:"range,omitempty"`
	Type   *string `json:"type,omitempty"`
}

// BackgroundEntry defines model for BackgroundEntry.
type BackgroundEntry struct {
	Feat   *string   `json:"feat,omitempty"`
	Id     *string   `json:"id,omitempty"`
	Name   *string   `json:"name,omitempty"`
	Skills *[]string `json:"skills,omitempty"`
}

// BuildRequest defines model for BuildRequest.
type BuildRequest struct {
	AbilityMethod  *BuildRequestAbilityMethod `json:"abilityMethod,omitempty"`
	AbilityScores  AbilityScores              `json:"abilityScores"`
	BackgroundId   string                     `json:"backgroundId"`
	Classes        []ClassReq                 `json:"classes"`
	Feats          *[]string                  `json:"feats,omitempty"`
	Level          int                        `json:"level"`
	Name           string                     `json:"name"`
	Skills         []string                   `json:"skills"`
	SpeciesId      string                     `json:"speciesId"`
	SpeciesVariant *string                    `json:"speciesVariant,omitempty"`
	Spells         *[]string                  `json:"spells,omitempty"`
}

// BuildRequestAbilityMethod defines model for BuildRequest.AbilityMethod.
type BuildRequestAbilityMethod string

// BuildResponse defines model for BuildResponse.
type BuildResponse struct {
	Classes  *[]string       `json:"classes,omitempty"`
	Event    *Event          `json:"event,omitempty"`
	Features *[]FeatureView  `json:"features,omitempty"`
	Id       *string         `json:"id,omitempty"`
	Sheet    *CharacterSheet `json:"sheet,omitempty"`
	Yaml     *string         `json:"yaml,omitempty"`
}

// CharacterCreatedEvent defines model for CharacterCreatedEvent.
type CharacterCreatedEvent struct {
	AbilityMethod  *string            `json:"abilityMethod,omitempty"`
	AbilityScores  *AbilityScores     `json:"abilityScores,omitempty"`
	BackgroundId   *string            `json:"backgroundId,omitempty"`
	CharacterId    *string            `json:"characterId,omitempty"`
	Classes        *[]ClassEntryEvent `json:"classes,omitempty"`
	Feats          *[]string          `json:"feats,omitempty"`
	Level          *int               `json:"level,omitempty"`
	MaxHP          *int               `json:"maxHP,omitempty"`
	Name           *string            `json:"name,omitempty"`
	SavingThrows   *[]string          `json:"savingThrows,omitempty"`
	Skills         *map[string]string `json:"skills,omitempty"`
	SpeciesId      *string            `json:"speciesId,omitempty"`
	SpeciesVariant *string            `json:"speciesVariant,omitempty"`
	Spells         *[]string          `json:"spells,omitempty"`
}

// CharacterSheet defines model for CharacterSheet.
type CharacterSheet struct {
	AbilityScores *AbilityScores  `json:"abilityScores,omitempty"`
	Ac            *int            `json:"ac,omitempty"`
	Attacks       *[]Attack       `json:"attacks,omitempty"`
	Background    *string         `json:"background,omitempty"`
	Classes       *[]ClassSummary `json:"classes,omitempty"`
	Features      *[]FeatureView  `json:"features,omitempty"`
	Hp            *HP             `json:"hp,omitempty"`
	Id            *string         `json:"id,omitempty"`
	Level         *int            `json:"level,omitempty"`
	Name          *string         `json:"name,omitempty"`
	SavingThrows  *map[string]int `json:"savingThrows,omitempty"`
	Skills        *map[string]int `json:"skills,omitempty"`
	Species       *string         `json:"species,omitempty"`
	SpellSlots    *map[string]int `json:"spellSlots,omitempty"`
	Spells        *[]string       `json:"spells,omitempty"`
}

// CharacterSummary defines model for CharacterSummary.
type CharacterSummary struct {
	Classes   *string    `json:"classes,omitempty"`
	Level     *int       `json:"level,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Species   *string    `json:"species,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ClassEntry defines model for ClassEntry.
type ClassEntry struct {
	Features       *[]FeatureDef      `json:"features,omitempty"`
	HitDie         *string            `json:"hitDie,omitempty"`
	Id             *string            `json:"id,omitempty"`
	Name           *string            `json:"name,omitempty"`
	PrimaryAbility *[]string          `json:"primaryAbility,omitempty"`
	SavingThrows   *[]string          `json:"savingThrows,omitempty"`
	SkillChoices   *int               `json:"skillChoices,omitempty"`
	SkillPool      *[]string          `json:"skillPool,omitempty"`
	Spellcaster    *bool              `json:"spellcaster,omitempty"`
	Spellcasting   *SpellcastingEntry `json:"spellcasting,omitempty"`
	SubClasses     *[]SubClassEntry   `json:"subClasses,omitempty"`
	SubclassLevel  *int               `json:"subclassLevel,omitempty"`
}

// ClassEntryEvent defines model for ClassEntryEvent.
type ClassEntryEvent struct {
	ClassId *string `json:"classId,omitempty"`
	Level   *int    `json:"level,omitempty"`
}

// ClassReq defines model for ClassReq.
type ClassReq struct {
	Id    string `json:"id"`
	Level int    `json:"level"`
}

// ClassSummary defines model for ClassSummary.
type ClassSummary struct {
	Id       *string `json:"id,omitempty"`
	Level    *int    `json:"level,omitempty"`
	Name     *string `json:"name,omitempty"`
	Subclass *string `json:"subclass,omitempty"`
}

// ContentResponse defines model for ContentResponse.
type ContentResponse struct {
	Abilities          *[]AbilityEntry       `json:"abilities,omitempty"`
	Backgrounds        *[]BackgroundEntry    `json:"backgrounds,omitempty"`
	Classes            *[]ClassEntry         `json:"classes,omitempty"`
	Feats              *map[string]FeatEntry `json:"feats,omitempty"`
	Skills             *[]SkillEntry         `json:"skills,omitempty"`
	Species            *[]SpeciesEntry       `json:"species,omitempty"`
	SpellCasterClasses *[]string             `json:"spellCasterClasses,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    *string                 `json:"code,omitempty"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Error   *string                 `json:"error,omitempty"`
}

// Event defines model for Event.
type Event struct {
	CharacterCreated *CharacterCreatedEvent `json:"characterCreated,omitempty"`
	Type             *string                `json:"type,omitempty"`
}

// FeatEntry defines model for FeatEntry.
type FeatEntry struct {
	Description   *string                 `json:"description,omitempty"`
	Id            *string                 `json:"id,omitempty"`
	Name          *string                 `json:"name,omitempty"`
	Prerequisites *map[string]interface{} `json:"prerequisites,omitempty"`
}

// FeatureDef defines model for FeatureDef.
type FeatureDef struct {
	Id    *string `json:"id,omitempty"`
	Level *int    `json:"level,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// FeatureView defines model for FeatureView.
type FeatureView struct {
	Class *string `json:"class,omitempty"`
	Id    *string `json:"id,omitempty"`
	Level *int    `json:"level,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// HP defines model for HP.
type HP struct {
	Current *int `json:"current,omitempty"`
	Max     *int `json:"max,omitempty"`
	Temp    *int `json:"temp,omitempty"`
}

// Health defines model for Health.
type Health struct {
	Status    *HealthStatus `json:"status,omitempty"`
	Timestamp *time.Time    `json:"timestamp,omitempty"`
	Version   *string       `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// SaveCharacterRequest defines model for SaveCharacterRequest.
type SaveCharacterRequest struct {
	Abilities       *map[string]int                      `json:"abilities,omitempty"`
	AbilityMethod   *string                              `json:"abilityMethod,omitempty"`
	BackgroundId    *string                              `json:"backgroundId,omitempty"`
	BackgroundName  *string                              `json:"backgroundName,omitempty"`
	BgAge           *string                              `json:"bgAge,omitempty"`
	BgAlignment     *string                              `json:"bgAlignment,omitempty"`
	BgBond          *string                              `json:"bgBond,omitempty"`
	BgEyes          *string                              `json:"bgEyes,omitempty"`
	BgFaith         *string                              `json:"bgFaith,omitempty"`
	BgFlaw          *string                              `json:"bgFlaw,omitempty"`
	BgHair          *string                              `json:"bgHair,omitempty"`
	BgHeight        *string                              `json:"bgHeight,omitempty"`
	BgIdeal         *string                              `json:"bgIdeal,omitempty"`
	BgNotes         *string                              `json:"bgNotes,omitempty"`
	BgSkin          *string                              `json:"bgSkin,omitempty"`
	BgTrait         *string                              `json:"bgTrait,omitempty"`
	BgWeight        *string                              `json:"bgWeight,omitempty"`
	Classes         *[]SavedClass                        `json:"classes,omitempty"`
	CreatedAt       *time.Time                           `json:"createdAt,omitempty"`
	Equipment       *[]string                            `json:"equipment,omitempty"`
	Feats           *[]string                            `json:"feats,omitempty"`
	Level           *int                                 `json:"level,omitempty"`
	Name            *string                              `json:"name,omitempty"`
	ProgressionType *SaveCharacterRequestProgressionType `json:"progressionType,omitempty"`
	Skills          *[]string                            `json:"skills,omitempty"`
	SpeciesHybrid   *string                              `json:"speciesHybrid,omitempty"`
	SpeciesId       *string                              `json:"speciesId,omitempty"`
	SpeciesVariant  *string                              `json:"speciesVariant,omitempty"`
	Spells          *[]string                            `json:"spells,omitempty"`
	SubclassId      *string                              `json:"subclassId,omitempty"`
	UpdatedAt       *time.Time                           `json:"updatedAt,omitempty"`
	Xp              *int                                 `json:"xp,omitempty"`
}

// SaveCharacterRequestProgressionType defines model for SaveCharacterRequest.ProgressionType.
type SaveCharacterRequestProgressionType string

// SavedCharacter defines model for SavedCharacter.
type SavedCharacter struct {
	Abilities       *map[string]int                `json:"abilities,omitempty"`
	AbilityMethod   *string                        `json:"abilityMethod,omitempty"`
	BackgroundId    *string                        `json:"backgroundId,omitempty"`
	BackgroundName  *string                        `json:"backgroundName,omitempty"`
	BgAge           *string                        `json:"bgAge,omitempty"`
	BgAlignment     *string                        `json:"bgAlignment,omitempty"`
	BgBond          *string                        `json:"bgBond,omitempty"`
	BgEyes          *string                        `json:"bgEyes,omitempty"`
	BgFaith         *string                        `json:"bgFaith,omitempty"`
	BgFlaw          *string                        `json:"bgFlaw,omitempty"`
	BgHair          *string                        `json:"bgHair,omitempty"`
	BgHeight        *string                        `json:"bgHeight,omitempty"`
	BgIdeal         *string                        `json:"bgIdeal,omitempty"`
	BgNotes         *string                        `json:"bgNotes,omitempty"`
	BgSkin          *string                        `json:"bgSkin,omitempty"`
	BgTrait         *string                        `json:"bgTrait,omitempty"`
	BgWeight        *string                        `json:"bgWeight,omitempty"`
	Classes         *[]SavedClass                  `json:"classes,omitempty"`
	CreatedAt       *time.Time                     `json:"createdAt,omitempty"`
	Equipment       *[]string                      `json:"equipment,omitempty"`
	Feats           *[]string                      `json:"feats,omitempty"`
	Level           *int                           `json:"level,omitempty"`
	Name            *string                        `json:"name,omitempty"`
	ProgressionType *SavedCharacterProgressionType `json:"progressionType,omitempty"`
	Skills          *[]string                      `json:"skills,omitempty"`
	SpeciesHybrid   *string                        `json:"speciesHybrid,omitempty"`
	SpeciesId       *string                        `json:"speciesId,omitempty"`
	SpeciesVariant  *string                        `json:"speciesVariant,omitempty"`
	Spells          *[]string                      `json:"spells,omitempty"`
	SubclassId      *string                        `json:"subclassId,omitempty"`
	UpdatedAt       *time.Time                     `json:"updatedAt,omitempty"`
	Xp              *int                           `json:"xp,omitempty"`
}

// SavedCharacterProgressionType defines model for SavedCharacter.ProgressionType.
type SavedCharacterProgressionType string

// SavedClass defines model for SavedClass.
type SavedClass struct {
	Id         *string `json:"id,omitempty"`
	Level      *int    `json:"level,omitempty"`
	Name       *string `json:"name,omitempty"`
	SubclassId *string `json:"subclassId,omitempty"`
}

// SkillEntry defines model for SkillEntry.
type SkillEntry struct {
	Ability *string `json:"ability,omitempty"`
	Id      *string `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// SpeciesEntry defines model for SpeciesEntry.
type SpeciesEntry struct {
	Id       *string         `json:"id,omitempty"`
	Name     *string         `json:"name,omitempty"`
	Size     *string         `json:"size,omitempty"`
	Speed    *int            `json:"speed,omitempty"`
	Variants *[]VariantEntry `json:"variants,omitempty"`
}

// SpellEntry defines model for SpellEntry.
type SpellEntry struct {
	Attack        *bool   `json:"attack,omitempty"`
	Concentration *bool   `json:"concentration,omitempty"`
	Damage        *string `json:"damage,omitempty"`
	Duration      *string `json:"duration,omitempty"`
	Id            *string `json:"id,omitempty"`
	Level         *int    `json:"level,omitempty"`
	Name          *string `json:"name,omitempty"`
	Range         *string `json:"range,omitempty"`
	Ritual        *bool   `json:"ritual,omitempty"`
	Save          *string `json:"save,omitempty"`
	School        *string `json:"school,omitempty"`
	Time          *string `json:"time,omitempty"`
}

// SpellcastingEntry defines model for SpellcastingEntry.
type SpellcastingEntry struct {
	Ability        *string              `json:"ability,omitempty"`
	CantripsKnown  *[]int               `json:"cantripsKnown,omitempty"`
	PreparedSpells *[]int               `json:"preparedSpells,omitempty"`
	RitualCasting  *bool                `json:"ritualCasting,omitempty"`
	SpellLists     *map[string][]string `json:"spellLists,omitempty"`
	SpellSlots     *map[string]int      `json:"spellSlots,omitempty"`
	SpellsKnown    *[]int               `json:"spellsKnown,omitempty"`
	Type           *string              `json:"type,omitempty"`
}

// SpellsResponse defines model for SpellsResponse.
type SpellsResponse struct {
	Cantrips *[]SpellEntry   `json:"cantrips,omitempty"`
	Leveled  *[][]SpellEntry `json:"leveled,omitempty"`
}

// SubClassEntry defines model for SubClassEntry.
type SubClassEntry struct {
	Description *string `json:"description,omitempty"`
	Id          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// VariantEntry defines model for VariantEntry.
type VariantEntry struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// GetSpellsParams defines parameters for GetSpells.
type GetSpellsParams struct {
	// Class Class ID to filter spells
	Class *string `form:"class,omitempty" json:"class,omitempty"`

	// Level Maximum spell level (1-9)
	Level *int `form:"level,omitempty" json:"level,omitempty"`

	// Lvl Character level for class spell list (1-20)
	Lvl *int `form:"lvl,omitempty" json:"lvl,omitempty"`
}

// BuildCharacterJSONRequestBody defines body for BuildCharacter for application/json ContentType.
type BuildCharacterJSONRequestBody = BuildRequest

// SaveCharacterJSONRequestBody defines body for SaveCharacter for application/json ContentType.
type SaveCharacterJSONRequestBody = SaveCharacterRequest

// UpdateCharacterJSONRequestBody defines body for UpdateCharacter for application/json ContentType.
type UpdateCharacterJSONRequestBody = SaveCharacterRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Build a character from choices
	// (POST /build)
	BuildCharacter(w http.ResponseWriter, r *http.Request)
	// List all saved characters
	// (GET /characters)
	ListCharacters(w http.ResponseWriter, r *http.Request)
	// Save a character
	// (POST /characters)
	SaveCharacter(w http.ResponseWriter, r *http.Request)
	// Delete a character
	// (DELETE /characters/{name})
	DeleteCharacter(w http.ResponseWriter, r *http.Request, name string)
	// Get a character by name
	// (GET /characters/{name})
	GetCharacter(w http.ResponseWriter, r *http.Request, name string)
	// Update a character
	// (PUT /characters/{name})
	UpdateCharacter(w http.ResponseWriter, r *http.Request, name string)
	// Get all content packs (classes, species, backgrounds, feats, abilities, skills)
	// (GET /content)
	GetContent(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
	// Get spells, optionally filtered by class and level
	// (GET /spells)
	GetSpells(w http.ResponseWriter, r *http.Request, params GetSpellsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Build a character from choices
// (POST /build)
func (_ Unimplemented) BuildCharacter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all saved characters
// (GET /characters)
func (_ Unimplemented) ListCharacters(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Save a character
// (POST /characters)
func (_ Unimplemented) SaveCharacter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a character
// (DELETE /characters/{name})
func (_ Unimplemented) DeleteCharacter(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a character by name
// (GET /characters/{name})
func (_ Unimplemented) GetCharacter(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a character
// (PUT /characters/{name})
func (_ Unimplemented) UpdateCharacter(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all content packs (classes, species, backgrounds, feats, abilities, skills)
// (GET /content)
func (_ Unimplemented) GetContent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get spells, optionally filtered by class and level
// (GET /spells)
func (_ Unimplemented) GetSpells(w http.ResponseWriter, r *http.Request, params GetSpellsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// BuildCharacter operation middleware
func (siw *ServerInterfaceWrapper) BuildCharacter(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BuildCharacter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListCharacters operation middleware
func (siw *ServerInterfaceWrapper) ListCharacters(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCharacters(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SaveCharacter operation middleware
func (siw *ServerInterfaceWrapper) SaveCharacter(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveCharacter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteCharacter operation middleware
func (siw *ServerInterfaceWrapper) DeleteCharacter(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCharacter(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetCharacter operation middleware
func (siw *ServerInterfaceWrapper) GetCharacter(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCharacter(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateCharacter operation middleware
func (siw *ServerInterfaceWrapper) UpdateCharacter(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCharacter(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetContent operation middleware
func (siw *ServerInterfaceWrapper) GetContent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSpells operation middleware
func (siw *ServerInterfaceWrapper) GetSpells(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSpellsParams

	// ------------- Optional query parameter "class" -------------

	err = runtime.BindQueryParameter("form", true, false, "class", r.URL.Query(), &params.Class)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "class", Err: err})
		return
	}

	// ------------- Optional query parameter "level" -------------

	err = runtime.BindQueryParameter("form", true, false, "level", r.URL.Query(), &params.Level)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "level", Err: err})
		return
	}

	// ------------- Optional query parameter "lvl" -------------

	err = runtime.BindQueryParameter("form", true, false, "lvl", r.URL.Query(), &params.Lvl)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lvl", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpells(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/build", wrapper.BuildCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/characters", wrapper.ListCharacters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/characters", wrapper.SaveCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/characters/{name}", wrapper.DeleteCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/characters/{name}", wrapper.GetCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/characters/{name}", wrapper.UpdateCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/content", wrapper.GetContent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/spells", wrapper.GetSpells)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xaXXPbttL+Kxi870U6w0Sym3Za3TmyW3uaD0/kk56ZHF9A5EpCDQIMCMrRyei/nwFA",
	"8ROgyJh2fJNYJLBY7D549gP8hkMRJ4IDVymefcNpuIGYmD/PlpRRtbvgSu7070SKBKSiYN7SSP+rdgng",
	"GU6VpHyN9wHmJAbHi31weCKW/0Co9NBc/iIU0oqsLzC/PNP/xeQrjbMYz36eBjim3P44KeRRrmANUguc",
	"f3g/cMb5xb8Hzrh6fzNwxuLm48AZf18tBs3YB1jCl4xKiPDss1nQbs2axCptxQbGrLcubyhFwru2G5aC",
	"Z2nFoxU9IxKTNQyBQYAl4Z4p9kEv5Lwh4d1aioxHHnCugCjnIsNQG+D0jjJm8a4gTjsUx0RKsvPom1EW",
	"fYQvGaSqrSyx5+AdqI0w6gHXjv6MU0V4RGSEA5wIytXLZbbDAZaCsYoLS0VI80D9v4QVnuH/m5RnfJIf",
	"8En99O0DvCyMeuU2UshImkLdGF0rzPX4j/BFz40pv7JzTpoGC4y3Btk4wAy2wGqH5PTosTo4OSZf3wJf",
	"qw2e/fraTDr8PAnGQECA0wRCCqnHjvnbT0RSwpVvyHDYVTnA7LV0WcO7VQ0PtmzCp9j5rR/QaSJ4Cm1E",
	"u5By1GiwBWuNLkxdmEE5ZjI5AI1/2AmfKNy7VvcQQ7oBOKrUfEMkCRXIhRm9D/COxKwnlxWT5xKIguji",
	"YIYjJPHkp/+g55jsYOi78OmYvNA+/jH5enntfuWnf7KlfH2zkeJ+KAUUtEGiiCoqOGHXNY/6RJTQ+DE0",
	"4kfo4nAYnND8TuCR0O0TYvKR/njK8xeHK0pojwfcRRbHRO58qB2TmTbJMQGX1x0M1nEiesP+CIQrItsY",
	"7nsOOoVYqPsxvmBCjbDIqIclR0hXcBzHWR3GyZJIx5Qzc2pXQsY6Lcb62UtFTYbQJ0IVTO1OtL8H7Oew",
	"cmKdqnMKo2TuiaTa/jnfDCTvh9H+fCNo6MOdGXEtBBucUjIWklSBrIxfCsGA8NoALeCIExaVsdaxWkC2",
	"nA+kwkU+pZDR0jpbGri/9eG6G2+eXMiIvBpId96VdIXSt7sxvOxo5OW0TLhvfQp5mWNMhs8d0zdJFVwB",
	"V/6M3+YAdAB2at2lzqjdX2azL+AQ+/1pameG6os7x6iwKdkVOPsdRT3cfw7LGNFPmh3fJY+xuWGj+fBa",
	"z7XdCymF7KgoReQGcgSKUFZdtZQJWmZPhPuoplGd9S4Fa9XcsO5WiYuWOhGkoaSJRtpIQRIMO6VUgcuG",
	"PvXyCP54DNWxsMmT3TFhiE3G0clWlA1VMimhVpHVq1BPPgpx0jduXQJhatNeOVVE2WbtoYUo7pydQp38",
	"pYrYFfvkhQHegkzdsHNpuCBbKM5CpfNJGPuwwrPPR+iHbCEqpuN90Nxobw/d5rpUpHXHrgcUEMdbNEeb",
	"LOWA974ju1yfrb1vGF3zGDzdgOX6jfDUwMv1xc5TQizXfxBqweZ6x8i959UlodL3Cuh641PyKgLCPO/e",
	"C+VVc3FHuefVjSTUt9zffl2G5goWaIaIXJmHjQj9a7EAa2pODv7sXyuM2zfrCB5iLSHVrHCTR7cD7cSU",
	"QaoE17v6mjgp6AF99cvdUtLOpthTtszKZNqz6uAi3NisZyioYO4p6gXnFp16lfmor2E4QgbjXLmauz7w",
	"2jrAKf2vt+0CkduKW4uv/sSRA9KTbns26TdvcZPb7hKEgofAlSSNFLIypONWN8paEx8hz+q6JJZUZbXo",
	"UO2AkK3HVeEm77c4E6H+uGo0TQYBOyRcSZqkf3Fxz1380k4tCoJJJCREQrTwklPHZGuyedkZ8vSO3tK0",
	"u5btT4ju3up4TdrvseGAAsyauaMYzV05pJzuKM7NCbFcUkgbQWwPEqm17x652HQpUOO90b8w0o8oX4nW",
	"XvD5f7Lp9PTXc/TLq18AFaUBso/RnMQJoWuO3hFO1iDR2fWVjtJUMS3/TIaEZ3H+tKiL8PTV6aup1lAk",
	"wElC8Qz//Ork1RQHOCFqY/Y0WWaUmX0lwlZEeseGVHVotRfrZa1im4eQqjci2tk+iGnEmVOUJIyGZurk",
	"n9T6yCLjaJus+jnKvt6iVDID88CC3yh9Op2OvXZ+tMzidd/oAQoVfRd0T9UGpYeL9dcjqlJvOTlU+UQY",
	"jYxkZFtJe5MJ5d1Z6ytEKrqupIhRmHf/9eBJ8c4Ycg0Ol2venZfDHmj7fk3N5iVVmy5axtBqIrGq7NZa",
	"guZbLe1iRhLGkA7IEaqYQIcyJ+xr7YJHQr2zJdEL/Sej6lBtbLTNXJKRsd5zw7zeQBXyTZRPvml63lvK",
	"ZaCg7etz87zq7YRIEoM9JJ+/YV3GG8bEB7I/fM5Ud1RQ2XMzGNy2nPi6HQZKW1tdc2u/fjprlxpwodDK",
	"fKNQN7i1Vt3kgZtI/gT15Fad/pCjERFFnqGv/gRVCwfLHTIm1rSXORz2L9MYeAqfPSc2/TGQyZswz4BP",
	"nx1sLQwdrF7q5+WbfMgjOrl59ezaoh2CZDmmdSwZQ7k6KCHhXYpe5N3dAOVdwQBVrpwDZJqoASouBwJk",
	"O5Y/WeNsiisYp23yG5pHtEu+gsMcH/5qGMAOReEGwjurfdnl9Hk2bzW0KKlheW1DdHWOlEArykzacpho",
	"yOtLBnJXspe9peuiq6C5xDv7pYWVi0ytjF6cvPz9J88Sh6+ZyyWKbzV+P/aphj9BsOuuhERmCwdtdKb7",
	"4uTl6dSrzdajy9HvRh411tYbHA4M2RFdJ8r6OUAisa0ctssRAJEOfNZMhEfWdHaNFOTWDaRzPUiYuw5k",
	"R+EAZ5LhGd4olcwmEyZCwjYiVbPfpr9NJ7q+3t/u/xcAAP//C4LmRL80AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
