/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Arcanum API
 * D&D 5.5e Character & Campaign Manager API
 * OpenAPI spec version: 0.2.0
 */
export type HealthStatus = typeof HealthStatus[keyof typeof HealthStatus];


export const HealthStatus = {
  ok: 'ok',
} as const;

export interface Health {
  status?: HealthStatus;
  version?: string;
  timestamp?: string;
}

export type ErrorResponseDetails = { [key: string]: unknown };

export interface ErrorResponse {
  error?: string;
  code?: string;
  details?: ErrorResponseDetails;
}

export type FeatEntryPrerequisites = { [key: string]: unknown };

export interface FeatEntry {
  id?: string;
  name?: string;
  description?: string;
  prerequisites?: FeatEntryPrerequisites;
}

export type ContentResponseFeats = {[key: string]: FeatEntry};

export interface SubClassEntry {
  id?: string;
  name?: string;
  description?: string;
}

export interface FeatureDef {
  level?: number;
  id?: string;
  name?: string;
}

export type SpellcastingEntrySpellSlots = {[key: string]: number};

export type SpellcastingEntrySpellLists = {[key: string]: string[]};

export interface SpellcastingEntry {
  type?: string;
  ability?: string;
  cantripsKnown?: number[];
  preparedSpells?: number[];
  spellsKnown?: number[];
  spellSlots?: SpellcastingEntrySpellSlots;
  ritualCasting?: boolean;
  spellLists?: SpellcastingEntrySpellLists;
}

export interface ClassEntry {
  id?: string;
  name?: string;
  hitDie?: string;
  savingThrows?: string[];
  primaryAbility?: string[];
  skillChoices?: number;
  skillPool?: string[];
  spellcaster?: boolean;
  subClasses?: SubClassEntry[];
  subclassLevel?: number;
  features?: FeatureDef[];
  spellcasting?: SpellcastingEntry;
}

export interface BackgroundEntry {
  id?: string;
  name?: string;
  skills?: string[];
  feat?: string;
}

export interface VariantEntry {
  id?: string;
  name?: string;
}

export interface SpeciesEntry {
  id?: string;
  name?: string;
  size?: string;
  speed?: number;
  variants?: VariantEntry[];
}

export interface AbilityEntry {
  id?: string;
  name?: string;
}

export interface SkillEntry {
  id?: string;
  name?: string;
  ability?: string;
}

export interface ContentResponse {
  classes?: ClassEntry[];
  backgrounds?: BackgroundEntry[];
  species?: SpeciesEntry[];
  abilities?: AbilityEntry[];
  skills?: SkillEntry[];
  feats?: ContentResponseFeats;
  spellCasterClasses?: string[];
}

export interface SpellEntry {
  id?: string;
  name?: string;
  level?: number;
  school?: string;
  time?: string;
  range?: string;
  duration?: string;
  concentration?: boolean;
  damage?: string;
  save?: string;
  attack?: boolean;
  ritual?: boolean;
}

export interface SpellsResponse {
  cantrips?: SpellEntry[];
  leveled?: SpellEntry[][];
}

export type BuildRequestAbilityMethod = typeof BuildRequestAbilityMethod[keyof typeof BuildRequestAbilityMethod];


export const BuildRequestAbilityMethod = {
  standard: 'standard',
  'point-buy': 'point-buy',
  roll: 'roll',
} as const;

export interface ClassReq {
  id: string;
  /**
     * @minimum 1
     * @maximum 20
     */
  level: number;
}

export interface AbilityScores {
  /**
     * @minimum 1
     * @maximum 30
     */
  STR: number;
  /**
     * @minimum 1
     * @maximum 30
     */
  DEX: number;
  /**
     * @minimum 1
     * @maximum 30
     */
  CON: number;
  /**
     * @minimum 1
     * @maximum 30
     */
  INT: number;
  /**
     * @minimum 1
     * @maximum 30
     */
  WIS: number;
  /**
     * @minimum 1
     * @maximum 30
     */
  CHA: number;
}

export interface BuildRequest {
  /**
     * @minLength 1
     * @maxLength 64
     */
  name: string;
  /** @minItems 1 */
  classes: ClassReq[];
  backgroundId: string;
  speciesId: string;
  speciesVariant?: string;
  /**
     * @minimum 1
     * @maximum 20
     */
  level: number;
  abilityScores: AbilityScores;
  abilityMethod?: BuildRequestAbilityMethod;
  skills: string[];
  spells?: string[];
  feats?: string[];
}

export interface ClassSummary {
  id?: string;
  name?: string;
  level?: number;
  subclass?: string;
}

export interface Hp {
  current?: number;
  max?: number;
  temp?: number;
}

export interface Attack {
  name?: string;
  bonus?: number;
  damage?: string;
  type?: string;
  range?: string;
}

export interface FeatureView {
  class?: string;
  level?: number;
  name?: string;
  id?: string;
}

export type CharacterSheetSavingThrows = {[key: string]: number};

export type CharacterSheetSkills = {[key: string]: number};

export type CharacterSheetSpellSlots = {[key: string]: number};

export interface CharacterSheet {
  id?: string;
  name?: string;
  level?: number;
  classes?: ClassSummary[];
  species?: string;
  background?: string;
  abilityScores?: AbilityScores;
  hp?: Hp;
  ac?: number;
  savingThrows?: CharacterSheetSavingThrows;
  skills?: CharacterSheetSkills;
  attacks?: Attack[];
  spellSlots?: CharacterSheetSpellSlots;
  spells?: string[];
  features?: FeatureView[];
}

export interface ClassEntryEvent {
  classId?: string;
  level?: number;
}

export type CharacterCreatedEventSkills = {[key: string]: string};

export interface CharacterCreatedEvent {
  characterId?: string;
  name?: string;
  speciesId?: string;
  speciesVariant?: string;
  backgroundId?: string;
  level?: number;
  abilityScores?: AbilityScores;
  maxHP?: number;
  savingThrows?: string[];
  skills?: CharacterCreatedEventSkills;
  spells?: string[];
  feats?: string[];
  abilityMethod?: string;
  classes?: ClassEntryEvent[];
}

export interface Event {
  type?: string;
  characterCreated?: CharacterCreatedEvent;
}

export interface BuildResponse {
  id?: string;
  sheet?: CharacterSheet;
  classes?: string[];
  event?: Event;
  yaml?: string;
  features?: FeatureView[];
}

export type SavedCharacterAbilities = {[key: string]: number};

export type SavedCharacterProgressionType = typeof SavedCharacterProgressionType[keyof typeof SavedCharacterProgressionType];


export const SavedCharacterProgressionType = {
  milestone: 'milestone',
  xp: 'xp',
} as const;

export interface SavedClass {
  id?: string;
  name?: string;
  level?: number;
  subclassId?: string;
}

export interface SavedCharacter {
  name?: string;
  classes?: SavedClass[];
  backgroundId?: string;
  backgroundName?: string;
  speciesId?: string;
  speciesVariant?: string;
  speciesHybrid?: string;
  level?: number;
  abilityMethod?: string;
  abilities?: SavedCharacterAbilities;
  skills?: string[];
  spells?: string[];
  feats?: string[];
  equipment?: string[];
  subclassId?: string;
  bgAlignment?: string;
  bgFaith?: string;
  bgTrait?: string;
  bgIdeal?: string;
  bgBond?: string;
  bgFlaw?: string;
  bgAge?: string;
  bgHeight?: string;
  bgWeight?: string;
  bgEyes?: string;
  bgSkin?: string;
  bgHair?: string;
  bgNotes?: string;
  xp?: number;
  progressionType?: SavedCharacterProgressionType;
  createdAt?: string;
  updatedAt?: string;
}

export type SaveCharacterRequest = SavedCharacter & {
  name?: string;
};

export interface CharacterSummary {
  name?: string;
  level?: number;
  classes?: string;
  species?: string;
  updatedAt?: string;
}

export type GetSpellsParams = {
/**
 * Class ID to filter spells
 */
class?: string;
/**
 * Maximum spell level (1-9)
 * @minimum 1
 * @maximum 9
 */
level?: number;
/**
 * Character level for class spell list (1-20)
 * @minimum 1
 * @maximum 20
 */
lvl?: number;
};

export const getHealthUrl = () => {




  return `/health`
}

/**
 * @summary Health check
 */
export const health = async ( options?: RequestInit): Promise<Health> => {

  const res = await fetch(getHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: Health = body ? JSON.parse(body) : {}
  return data
}



export const getGetContentUrl = () => {




  return `/content`
}

/**
 * @summary Get all content packs (classes, species, backgrounds, feats, abilities, skills)
 */
export const getContent = async ( options?: RequestInit): Promise<ContentResponse> => {

  const res = await fetch(getGetContentUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ContentResponse = body ? JSON.parse(body) : {}
  return data
}



export const getGetSpellsUrl = (params?: GetSpellsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/spells?${stringifiedParams}` : `/spells`
}

/**
 * @summary Get spells, optionally filtered by class and level
 */
export const getSpells = async (params?: GetSpellsParams, options?: RequestInit): Promise<SpellsResponse> => {

  const res = await fetch(getGetSpellsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SpellsResponse = body ? JSON.parse(body) : {}
  return data
}



export const getBuildCharacterUrl = () => {




  return `/build`
}

/**
 * @summary Build a character from choices
 */
export const buildCharacter = async (buildRequest: BuildRequest, options?: RequestInit): Promise<BuildResponse> => {

  const res = await fetch(getBuildCharacterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(buildRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: BuildResponse = body ? JSON.parse(body) : {}
  return data
}



export const getListCharactersUrl = () => {




  return `/characters`
}

/**
 * @summary List all saved characters
 */
export const listCharacters = async ( options?: RequestInit): Promise<CharacterSummary[]> => {

  const res = await fetch(getListCharactersUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CharacterSummary[] = body ? JSON.parse(body) : {}
  return data
}



export const getSaveCharacterUrl = () => {




  return `/characters`
}

/**
 * @summary Save a character
 */
export const saveCharacter = async (saveCharacterRequest: SaveCharacterRequest, options?: RequestInit): Promise<SavedCharacter> => {

  const res = await fetch(getSaveCharacterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(saveCharacterRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SavedCharacter = body ? JSON.parse(body) : {}
  return data
}



export const getGetCharacterUrl = (name: string,) => {




  return `/characters/${name}`
}

/**
 * @summary Get a character by name
 */
export const getCharacter = async (name: string, options?: RequestInit): Promise<SavedCharacter> => {

  const res = await fetch(getGetCharacterUrl(name),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SavedCharacter = body ? JSON.parse(body) : {}
  return data
}



export const getUpdateCharacterUrl = (name: string,) => {




  return `/characters/${name}`
}

/**
 * @summary Update a character
 */
export const updateCharacter = async (name: string,
    saveCharacterRequest: SaveCharacterRequest, options?: RequestInit): Promise<SavedCharacter> => {

  const res = await fetch(getUpdateCharacterUrl(name),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(saveCharacterRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SavedCharacter = body ? JSON.parse(body) : {}
  return data
}



export const getDeleteCharacterUrl = (name: string,) => {




  return `/characters/${name}`
}

/**
 * @summary Delete a character
 */
export const deleteCharacter = async (name: string, options?: RequestInit): Promise<void> => {

  const res = await fetch(getDeleteCharacterUrl(name),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: void = body ? JSON.parse(body) : undefined
  return data
}
